# Generated by Django 6.0.2 on 2026-02-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValentineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_to_unlock', models.DateField()),
                ('clue_question', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=100)),
                ('love_letter', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='memories/')),
                ('music', models.FileField(blank=True, null=True, upload_to='music/')),
            ],
        ),
    ]
